### ISSUE TITLE
Automatic events don't seem to be firing?

### ISSUE THREAD

**Issue by jaewun** [GeneaLabs/laravel-mixpanel#33]
Running the latest version of Laravel, 5.4.21

I can fire manual events perfectly fine but it seems like all the listeners just don't listen.

It seems like everything runs up to the event() helper being fired and then it just dies.

Any idea what could be causing this?

**Comment by jaewun** [comment]
I've debugged this and it seems Listeners\MixpanelEvent@handle is never firing?

When is Laravel instructed to attach this listener to Events\MixpanelEvent? It either has no way of knowing right now, or I'm completely missing something.

The only way I could get it to work was by registering the event and listener in my own EventServiceProvider manually, and when doing that all of the event details would be shoved into the event name as a json string, like the details are an array level too deep when they get to the mixpanel php library.

Is this intentional? Am I missing something? Or does it just not work?

**Comment by mikebronner** [comment]
Not sure, let me look into it. Might be a week or two before I can get to it. Thanks for reporting this issue.

**Comment by mikebronner** [comment]
@keithbrink Thanks for reporting that you are having the same issue. Will take a look this weekend. :)

**Comment by mikebronner** [comment]
@jaewun and @keithbrink: have you implement the javascript library and connected mixpanel to you website by configuring the web app in the mixpanel dashboard? I think that might be disconnect. A while back I removed php page tracking, as the mixpanel auto-tracking feature made that redundant, and gives you more insights. Can you confirm that is the case?

**Comment by mikebronner** [comment]
In the meanwhile I'm making some tweaks to the way the JS library is integrated and also updating documentation.

**Comment by keithbrink** [comment]
Mike‎, the autotracking is working fine, it's the login/registration events that aren't working.                                                                                                                                                                                                                From: Mike BronnerSent: Sunday, May 14, 2017 12:45To: GeneaLabs/laravel-mixpanelReply To: GeneaLabs/laravel-mixpanelCc: keithbrink; MentionSubject: Re: [GeneaLabs/laravel-mixpanel] Automatic events don't seem to be firing? (#33)@jaewun and @keithbrink: have you implement the javascript library and connected mixpanel to you website by configuring the web app in the mixpanel dashboard? I think that might be disconnect. A while back I removed php page tracking, as the mixpanel auto-tracking feature made that redundant, and gives you more insights. Can you confirm that is the case?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GeneaLabs/laravel-mixpanel","title":"GeneaLabs/laravel-mixpanel","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/GeneaLabs/laravel-mixpanel"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mikebronner in #33: @jaewun and @keithbrink: have you implement the javascript library and connected mixpanel to you website by configuring the web app in the mixpanel dashboard? I think that might be disconnect. A while back I removed php page tracking, as the mixpanel auto-tracking feature made that redundant, and gives you more insights. Can you confirm that is the case?"}],"action":{"name":"View Issue","url":"https://github.com/GeneaLabs/laravel-mixpanel/issues/33#issuecomment-301324551"}}}

**Comment by mikebronner** [comment]
Thanks for the clarification. Will report back in a bit.

**Comment by mikebronner** [comment]
Issue identified: event handler not registering properly. Working on a fix, hope to have it out in the next few hours.

**Comment by mikebronner** [comment]
This should now be fixed in the 0.6.8 release. Please let me know if you experience any issues. :) My apologies to everyone for the inconvenience and oversight on my end.
